"""Writes the appendix tables from the result CSVs."""
from pathlib import Path

import pandas as pd

import prep

OUT = prep.OUTPUT_DIR
DEST = Path(__file__).resolve().parents[1] / "latex" / "99-tables.tex"

cv_o = pd.read_csv(OUT / "cv_olist.csv")
cv_f = pd.read_csv(OUT / "cv_food.csv")
lc_o = pd.read_csv(OUT / "learning_curve_olist.csv")
fair = pd.read_csv(OUT / "fairness_olist_region.csv")
summ = pd.read_csv(OUT / "fairness_olist_summary.csv")
food_fair = pd.read_csv(OUT / "fairness_food.csv")


def fmt(v, dp=3):
    return "--" if pd.isna(v) else f"{v:.{dp}f}"


lines = []
add = lines.append

add("% Generated by analysis/make_tables.py. Do not edit by hand.")
add(r"\begin{table}[htbp]")
add(r"\caption{Evaluation protocols compared. Task 1 reported the first row of "
    r"each block as a point estimate. Spread is the standard deviation across folds.}")
add(r"\label{tab:cv}")
add(r"\begin{tabular}{llrr}")
add(r"\toprule")
add(r"Protocol & Model & Folds & Score \\")
add(r"\midrule")
add(r"\multicolumn{4}{l}{\textit{Olist: average precision, higher is better}} \\")
for _, r in cv_o.iterrows():
    score = fmt(r["mean"]) + ("" if pd.isna(r["sd"]) else f" $\\pm$ {r['sd']:.3f}")
    strategy = r["strategy"].replace("<", "$<$")
    add(f"{strategy} & {r['model']} & {int(r['folds'])} & {score} \\\\")
add(r"\midrule")
add(r"\multicolumn{4}{l}{\textit{Food delivery: MAE in minutes, lower is better}} \\")
for _, r in cv_f.iterrows():
    score = fmt(r["mean"]) + ("" if pd.isna(r["sd"]) else f" $\\pm$ {r['sd']:.3f}")
    strategy = r["strategy"].replace("<", "$<$")
    add(f"{strategy} & {r['model']} & {int(r['folds'])} & {score} \\\\")
add(r"\bottomrule")
add(r"\end{tabular}")
add(r"\end{table}")
add("")

add(r"\begin{table}[htbp]")
add(r"\caption{Olist learning curve. The support vector machine was capped at "
    r"15,000 rows in Task 1. Extending it to the full training set raises average "
    r"precision from 0.268 to 0.335 and costs 187 seconds against 1.0 second for "
    r"gradient boosting.}")
add(r"\label{tab:learning}")
add(r"\begin{tabular}{rrrrr}")
add(r"\toprule")
add(r"& \multicolumn{2}{c}{Gradient boosting} & \multicolumn{2}{c}{Support vector machine} \\")
add(r"\cmidrule(lr){2-3}\cmidrule(lr){4-5}")
add(r"Training rows & PR-AUC & Fit (s) & PR-AUC & Fit (s) \\")
add(r"\midrule")
for n in sorted(lc_o["n_train"].unique()):
    x = lc_o[(lc_o.n_train == n) & (lc_o.model == "XGBoost")].iloc[0]
    s = lc_o[(lc_o.n_train == n) & (lc_o.model == "SVM")].iloc[0]
    add(f"{int(n):,} & {x['score']:.3f} & {x['fit_seconds']:.1f} & "
        f"{s['score']:.3f} & {s['fit_seconds']:.1f} \\\\")
add(r"\bottomrule")
add(r"\end{tabular}")
add(r"\end{table}")
add("")

dpd = summ["demographic_parity_difference"].iloc[0]
eod = summ["equalized_odds_difference"].iloc[0]
add(r"\begin{table}[htbp]")
add(r"\caption{Fairlearn group metrics by Brazilian macro-region at the 70 per cent "
    r"recall operating point. Demographic parity difference is "
    f"{dpd:.3f}" + r" and equalised odds difference is " + f"{eod:.3f}" + r". "
    r"The North carries the highest rate of late deliveries and the highest rate "
    r"of missed warnings.}")
add(r"\label{tab:fairness}")
add(r"\begin{tabular}{lrrrrr}")
add(r"\toprule")
add(r"Region & Orders & Late & Flagged & Recall & Missed \\")
add(r"\midrule")
for _, r in fair.sort_values("false_negative_rate", ascending=False).iterrows():
    add(f"{r['group']} & {int(r['count']):,} & {r['base_rate']:.3f} & "
        f"{r['selection_rate']:.3f} & {r['recall']:.3f} & "
        f"{r['false_negative_rate']:.3f} \\\\")
add(r"\bottomrule")
add(r"\end{tabular}")
add(r"\end{table}")
add("")

sub = food_fair[food_fair["grouping"].isin(["city_type", "age_band"])]
add(r"\begin{table}[htbp]")
add(r"\caption{Fairlearn group metrics for the food delivery regression. The "
    r"rows with a missing courier age carry roughly 70 per cent more error than the rest, "
    r"so a data quality gap becomes a service quality gap. Semi-Urban holds 32 "
    r"test rows, which is too few to support a claim about it.}")
add(r"\label{tab:fairfood}")
add(r"\begin{tabular}{llrrr}")
add(r"\toprule")
add(r"Grouping & Group & Rows & MAE (min) & Mean signed error \\")
add(r"\midrule")
for _, r in sub.iterrows():
    group = "missing" if str(r["group"]) == "nan" else r["group"]
    add(f"{r['grouping'].replace('_', ' ')} & {group} & {int(r['count']):,} & "
        f"{r['mae']:.3f} & {r['mean_signed_error']:+.3f} \\\\")
add(r"\bottomrule")
add(r"\end{tabular}")
add(r"\end{table}")

DEST.write_text("\n".join(lines) + "\n")
print(f"wrote {DEST} ({len(lines)} lines)")
